'use client';

import { useApp } from '@/lib/app-context';
import { EMPRESA_HERO, FINANCE_HERO, MANAGER_HERO, MOCK_HUB_SCREENS } from '@/lib/mock-data';
import { BackIcon, OverlayHeader } from './OverlayHeader';

export function ScreenOverlay() {
  const { lang, screen, setScreen, tasks, toggleTask } = useApp();
  const active = MOCK_HUB_SCREENS.find((s) => s.key === screen);
  if (!active) return null;

  const openTasks = tasks.filter((tk) => !tk.done).length;
  const subtitle =
    active.key === 'tarefas'
      ? lang === 'pt'
        ? `Geradas pela 7M AI · ${openTasks} pendentes`
        : `Generated by 7M AI · ${openTasks} open`
      : active.sub[lang];

  return (
    <div
      className="animate-ovin absolute inset-0 z-[46] flex flex-col"
      style={{ background: 'radial-gradient(120% 70% at 80% -5%, #0d2a5e, #0B2149 52%, #08132C)' }}
    >
      <OverlayHeader onClose={() => setScreen(null)} icon={<BackIcon />} title={active.title[lang]} subtitle={subtitle} />
      <div className="appscroll min-h-0 flex-1 overflow-y-auto p-[18px_18px_40px]">
        {active.key === 'manager' && (
          <div className="rounded-[20px] border border-gold/[.24] p-[18px]" style={{ background: 'linear-gradient(150deg,rgba(201,154,46,.14),rgba(11,33,73,.2))' }}>
            <div className="flex items-center gap-3.5">
              <div className="h-[60px] w-[60px] flex-shrink-0 rounded-2xl bg-white/10" />
              <div className="min-w-0 flex-1">
                <div className="font-display text-lg font-bold text-white">{MANAGER_HERO.name}</div>
                <div className="mt-0.5 text-xs text-text-tertiary">{MANAGER_HERO.role[lang]}</div>
                <div className="mt-1 flex items-center gap-1.5 text-[11.5px] text-status-green">
                  <span className="h-1.5 w-1.5 rounded-full bg-status-green" />
                  {MANAGER_HERO.status[lang]}
                </div>
              </div>
            </div>
            <div className="mt-[15px] grid grid-cols-4 gap-2">
              {MANAGER_HERO.actions.map((a, i) => (
                <button key={i} className="flex flex-col items-center gap-[5px] rounded-[13px] border border-white/10 bg-white/[.06] p-[11px_4px]">
                  <span className="text-[16px]">{a.icon}</span>
                  <span className="text-[10.5px] font-semibold text-text">{a.label[lang]}</span>
                </button>
              ))}
            </div>
          </div>
        )}

        {active.key === 'financeiro' && (
          <div className="relative overflow-hidden rounded-[20px] border border-gold/40 p-5" style={{ background: 'linear-gradient(155deg,#12336e,#0b1e42)' }}>
            <div className="pointer-events-none absolute -right-[30px] -top-[30px] h-[130px] w-[130px] rounded-full" style={{ background: 'radial-gradient(circle, rgba(244,212,138,.2), transparent 70%)' }} />
            <div className="relative">
              <div className="flex items-center justify-between">
                <div className="whitespace-nowrap font-mono text-[10px] uppercase tracking-[.14em] text-gold">{FINANCE_HERO.label[lang]}</div>
                <span className="rounded-lg bg-status-green/[.14] px-2.5 py-[5px] text-[11px] font-bold text-status-green">{FINANCE_HERO.status[lang]}</span>
              </div>
              <div className="mt-2.5 font-display text-[26px] font-bold text-white">{FINANCE_HERO.plan}</div>
              <div className="mt-0.5 font-display text-xl font-bold text-gold-light">{FINANCE_HERO.price[lang]}</div>
              <div className="mt-2 text-xs text-text-tertiary">{FINANCE_HERO.next[lang]}</div>
              <button className="mt-[15px] w-full rounded-xl p-[13px] font-display text-sm font-bold text-navy" style={{ background: 'linear-gradient(140deg,#C99A2E,#F4D48A)' }}>
                Upgrade → 7M Scale
              </button>
            </div>
          </div>
        )}

        {active.key === 'empresa' && (
          <div className="flex items-center gap-3.5 rounded-[20px] border border-white/[.08] bg-white/[.035] p-[18px]">
            <div className="h-14 w-14 flex-shrink-0 rounded-2xl bg-gradient-to-br from-gold to-gold-light" />
            <div className="min-w-0 flex-1">
              <div className="font-display text-[19px] font-bold text-white">{EMPRESA_HERO.name}</div>
              <div className="mt-0.5 text-xs text-text-secondary">{EMPRESA_HERO.sub[lang]}</div>
            </div>
            <span className="flex-shrink-0 rounded-lg border border-gold/30 bg-gold/[.12] px-2.5 py-1.5 text-[10.5px] font-semibold text-gold-light">
              {EMPRESA_HERO.since[lang]}
            </span>
          </div>
        )}

        {active.key === 'tarefas' && (
          <div className="flex flex-col gap-2.5">
            {tasks.map((tk) => {
              const alta = tk.priority === 'high';
              const prioLabel = tk.done ? (lang === 'pt' ? 'Feito' : 'Done') : alta ? (lang === 'pt' ? 'Alta' : 'High') : lang === 'pt' ? 'Média' : 'Medium';
              const prioColor = tk.done ? '#8ea0bc' : alta ? '#F4776A' : '#F4D48A';
              const prioBg = tk.done ? 'rgba(255,255,255,.05)' : alta ? 'rgba(244,119,106,.14)' : 'rgba(201,154,46,.14)';
              const impacto = lang === 'pt' ? tk.impactoPt : tk.impactoEn;
              return (
                <div key={tk.id} className="rounded-[15px] border border-white/[.07] bg-white/[.03] p-[14px_15px]">
                  <div className="flex items-start gap-3">
                    <button
                      onClick={() => toggleTask(tk.id)}
                      className="mt-px flex h-6 w-6 flex-shrink-0 items-center justify-center rounded-lg text-[13px] text-navy"
                      style={{ background: tk.done ? '#F4D48A' : 'transparent', border: `1.8px solid ${tk.done ? '#F4D48A' : 'rgba(255,255,255,.28)'}` }}
                    >
                      {tk.done ? '✓' : ''}
                    </button>
                    <div className="min-w-0 flex-1">
                      <div className="text-[14.5px] font-semibold leading-[1.35]" style={{ color: tk.done ? '#7f93b5' : '#fff' }}>
                        {lang === 'pt' ? tk.titlePt : tk.titleEn}
                      </div>
                      <div className="mt-[9px] flex flex-wrap items-center gap-[7px]">
                        <span className="rounded-[7px] px-[9px] py-1 text-[10.5px] font-bold" style={{ color: prioColor, background: prioBg }}>
                          {prioLabel}
                        </span>
                        <span className="text-[11px] text-text-secondary">◷ {lang === 'pt' ? tk.prazoPt : tk.prazoEn}</span>
                        {tk.tempo && <span className="text-[11px] text-text-secondary">· {tk.tempo}</span>}
                        {impacto && <span className="text-[11px] text-ai-blue">↗ {impacto}</span>}
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}

        {active.key !== 'tarefas' &&
          active.sections.map((section, i) => (
            <div key={i} className="mt-[18px] first:mt-0">
              <div className="mb-[9px] font-mono text-[10px] uppercase tracking-[.14em] text-text-secondary">{section.header[lang]}</div>
              <div className="flex flex-col gap-2">
                {section.rows.map((row, j) => (
                  <div key={j} className="flex items-center gap-[13px] rounded-[14px] border border-white/[.07] bg-white/[.03] p-[13px_15px]">
                    <div
                      className="flex h-[38px] w-[38px] flex-shrink-0 items-center justify-center rounded-[11px] text-[16px] text-text"
                      style={{ background: row.iconBg ?? 'rgba(255,255,255,.06)' }}
                    >
                      {row.icon}
                    </div>
                    <div className="min-w-0 flex-1">
                      <div className="text-sm font-semibold text-text">{row.title[lang]}</div>
                      {row.sub && <div className="mt-0.5 text-[11.5px] text-text-secondary">{row.sub[lang]}</div>}
                    </div>
                    {row.right && (
                      <div
                        className="flex-shrink-0 whitespace-nowrap rounded-lg px-2.5 py-[5px] text-[11.5px] font-bold"
                        style={{ color: row.rightColor ?? '#8ea0bc', background: row.rightBg ?? 'transparent' }}
                      >
                        {row.right[lang]}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          ))}
      </div>
    </div>
  );
}
